const weapons = [

	{name: "52 Gal",
	sub: "Splash Wall",
	special: "Killer Wail 5.1",
	wclass: "Shooter",
	id: 0},

	{name: "52 Gal Deco",
	sub: "Curling Bomb",
	special: "Splattercolor Screen",
	wclass: "Shooter",
	id: 1},

	{name: "96 Gal",
	sub: "Sprinkler",
	special: "Ink Vac",
	wclass: "Shooter",
	id: 2},

	{name: "96 Gal Deco",
	sub: "Splash Wall",
	special: "Kraken Royale",
	wclass: "Shooter",
	id: 3},

	{name: "Aerospray MG",
	sub: "Fizzy Bomb",
	special: "Reefslider",
	wclass: "Shooter",
	id: 4},

	{name: "Aerospray RG",
	sub: "Sprinkler",
	special: "Booyah Bomb",
	wclass: "Shooter",
	id: 5},

	{name: "Annaki Splattershot Nova",
	sub: "Ink Mine",
	special: "Inkjet",
	wclass: "Shooter",
	id: 6},

	{name: "Ballpoint Splatling",
	sub: "Fizzy Bomb",
	special: "Inkjet",
	wclass: "Splatling",
	id: 7},

	{name: "Ballpoint Splatling Nouveau",
	sub: "Ink Mine",
	special: "Ink Vac",
	wclass: "Splatling",
	id: 8},

	{name: "Bamboozler 14 Mk I",
	sub: "Autobomb",
	special: "Killer Wail 5.1",
	wclass: "Charger",
	id: 9},

	{name: "Bamboozler 14 Mk II",
	sub: "Fizzy Bomb",
	special: "Super Chump",
	wclass: "Charger",
	id: 10},

	{name: "Big Swig Roller",
	sub: "Splash Wall",
	special: "Ink Vac",
	wclass: "Roller",
	id: 11},

	{name: "Big Swig Roller Express",
	sub: "Angle Shooter",
	special: "Ink Storm",
	wclass: "Roller",
	id: 12},

	{name: "Blaster",
	sub: "Autobomb",
	special: "Big Bubbler",
	wclass: "Blaster",
	id: 13},

	{name: "Bloblobber",
	sub: "Sprinkler",
	special: "Ink Storm",
	wclass: "Slosher",
	id: 14},

	{name: "Bloblobber Deco",
	sub: "Angle Shooter",
	special: "Kraken Royale",
	wclass: "Slosher",
	id: 15},

    {name: "Bulbz Tri-Stringer",
    sub: "Angle Shooter",
    special: "Inkjet",
    wclass: "Stringer",
	id: 16},

	{name: "Carbon Roller",
	sub: "Autobomb",
	special: "Zipcaster",
	wclass: "Roller",
	id: 17},

    {name: "Carbon Roller ANG-L",
    sub: "Fizzy Bomb",
    special: "Super Chump",
    wclass: "Roller",
	id: 18},

	{name: "Carbon Roller Deco",
	sub: "Burst Bomb",
	special: "Trizooka",
	wclass: "Roller",
	id: 19},

	{name: "Charcoal Decavitator",
	sub: "Splash Wall",
	special: "Inkjet",
	wclass: "Splatana",
	id: 20},

	{name: "Clash Blaster",
	sub: "Splat Bomb",
	special: "Trizooka",
	wclass: "Blaster",
	id: 21},

	{name: "Clash Blaster Neo",
	sub: "Curling Bomb",
	special: "Super Chump",
	wclass: "Blaster",
	id: 22},

	{name: "Classic Squiffer",
	sub: "Point Sensor",
	special: "Big Bubbler",
	wclass: "Charger",
	id: 23},

    {name: "Clawz 96 Gal",
    sub: "Angle Shooter",
    special: "Tacticooler",
    wclass: "Shooter",
	id: 24},

    {name: "Colorz Aerospray",
    sub: "Burst Bomb",
    special: "Splattercolor Screen",
    wclass: "Shooter",
	id: 25},

    {name: "Cometz Octobrush",
    sub: "Autobomb",
    special: "Kraken Royale",
    wclass: "Brush",
	id: 26},

	{name: "Custom Blaster",
	sub: "Point Sensor",
	special: "Triple Splashdown",
	wclass: "Blaster",
	id: 27},

	{name: "Custom Douser Dualies FF",
	sub: "Burst Bomb",
	special: "Triple Inkstrike",
	wclass: "Dualie",
	id: 28},

	{name: "Custom Dualie Squelchers",
	sub: "Squid Beakon",
	special: "Super Chump",
	wclass: "Dualie",
	id: 29},

	{name: "Custom E-liter 4K",
	sub: "Squid Beakon",
	special: "Kraken Royale",
	wclass: "Charger",
	id: 30},

	{name: "Custom E-liter 4K Scope",
	sub: "Squid Beakon",
	special: "Kraken Royale",
	wclass: "Charger",
	id: 31},

	{name: "Custom Explosher",
	sub: "Splash Wall",
	special: "Triple Splashdown",
	wclass: "Slosher",
	id: 32},

	{name: "Custom Goo Tuber",
	sub: "Fizzy Bomb",
	special: "Ultra Stamp",
	wclass: "Charger",
	id: 33},

	{name: "Custom Hydra Splatling",
	sub: "Ink Mine",
	special: "Splattercolor Screen",
	wclass: "Splatling",
	id: 34},

	{name: "Custom Jet Squelcher",
	sub: "Toxic Mist",
	special: "Ink Storm",
	wclass: "Shooter",
	id: 35},

	{name: "Custom Range Blaster",
	sub: "Splat Bomb",
	special: "Kraken Royale",
	wclass: "Blaster",
	id: 36},

	{name: "Custom Splattershot Jr",
	sub: "Torpedo",
	special: "Wave Breaker",
	wclass: "Shooter",
	id: 37},

	{name: "Custom Wellstring V",
	sub: "Point Sensor",
	special: "Wave Breaker",
	wclass: "Stringer",
	id: 38},

	{name: "Dapple Dualies",
	sub: "Squid Beakon",
	special: "Tacticooler",
	wclass: "Dualie",
	id: 39},

    {name: "Dapple Dualies NOC-T",
    sub: "Splat Bomb",
    special: "Killer Wail 5.1",
    wclass: "Dualie",
	id: 40},

	{name: "Dapple Dualies Nouveau",
	sub: "Torpedo",
	special: "Reefslider",
	wclass: "Dualie",
	id: 41},

	{name: "Dark Tetra Dualies",
	sub: "Autobomb",
	special: "Reefslider",
	wclass: "Dualie",
	id: 42},

	{name: "Douser Dualies FF",
	sub: "Ink Mine",
	special: "Killer Wail 5.1",
	wclass: "Dualie",
	id: 43},

	{name: "Dread Wringer",
	sub: "Suction Bomb",
	special: "Reefslider",
	wclass: "Slosher",
	id: 44},

	{name: "Dread Wringer D",
	sub: "Squid Beakon",
	special: "Wave Breaker",
	wclass: "Slosher",
	id: 45},

	{name: "Dualie Squelchers",
	sub: "Splat Bomb",
	special: "Wave Breaker",
	wclass: "Dualie",
	id: 46},

	{name: "Dynamo Roller",
	sub: "Sprinkler",
	special: "Tacticooler",
	wclass: "Roller",
	id: 47},

	{name: "E-liter 4K",
	sub: "Ink Mine",
	special: "Wave Breaker",
	wclass: "Charger",
	id: 48},

	{name: "E-liter 4K Scope",
	sub: "Ink Mine",
	special: "Wave Breaker",
	wclass: "Charger",
	id: 49},

	{name: "Enperry Splat Dualies",
	sub: "Curling Bomb",
	special: "Triple Splashdown",
	wclass: "Dualie",
	id: 50},

	{name: "Explosher",
	sub: "Point Sensor",
	special: "Ink Storm",
	wclass: "Slosher",
	id: 51},

	{name: "Flingza Roller",
	sub: "Ink Mine",
	special: "Tenta Missiles",
	wclass: "Roller",
	id: 52},

	{name: "Foil Flingza Roller",
	sub: "Suction Bomb",
	special: "Splattercolor Screen",
	wclass: "Roller",
	id: 53},

	{name: "Foil Squeezer",
	sub: "Autobomb",
	special: "Splattercolor Screen",
	wclass: "Shooter",
	id: 54},

	{name: "Forge Splattershot Pro",
	sub: "Suction Bomb",
	special: "Booyah Bomb",
	wclass: "Shooter",
	id: 55},

    {name: "Glamorz Splattershot",
    sub: "Burst Bomb",
    special: "Kraken Royale",
    wclass: "Shooter",
	id: 56},

    {name: "Gleamz Blaster",
    sub: "Squid Beakon",
    special: "Crab Tank",
    wclass: "Blaster",
	id: 57},

    {name: "Glitterz L-3 Nozzlenose",
    sub: "Splat Bomb",
    special: "Inkjet",
    wclass: "Shooter",
	id: 58},

	{name: "Glooga Dualies",
	sub: "Splash Wall",
	special: "Booyah Bomb",
	wclass: "Dualie",
	id: 59},

	{name: "Glooga Dualies Deco",
	sub: "Point Sensor",
	special: "Trizooka",
	wclass: "Dualie",
	id: 60},

	{name: "Goo Tuber",
	sub: "Torpedo",
	special: "Tenta Missiles",
	wclass: "Charger",
	id: 61},

	{name: "Gold Dynamo Roller",
	sub: "Splat Bomb",
	special: "Super Chump",
	wclass: "Roller",
	id: 62},

	{name: "H-3 Nozzlenose",
	sub: "Point Sensor",
	special: "Tacticooler",
	wclass: "Shooter",
	id: 63},

	{name: "H-3 Nozzlenose D",
	sub: "Splash Wall",
	special: "Big Bubbler",
	wclass: "Shooter",
	id: 64},

    {name: "H-3 Nozzlenose VIP-R",
    sub: "Suction Bomb",
    special: "Triple Inkstrike",
    wclass: "Shooter",
	id: 65},

	{name: "Heavy Edit Splatling",
	sub: "Curling Bomb",
	special: "Tacticooler",
	wclass: "Splatling",
	id: 66},

	{name: "Heavy Edit Splatling Nouveau",
	sub: "Splat Bomb",
	special: "Crab Tank",
	wclass: "Splatling",
	id: 67},

	{name: "Heavy Splatling",
	sub: "Sprinkler",
	special: "Wave Breaker",
	wclass: "Splatling",
	id: 68},

	{name: "Heavy Splatling Deco",
	sub: "Point Sensor",
	special: "Kraken Royale",
	wclass: "Splatling",
	id: 69},

	{name: "Hero Shot Replica",
	sub: "Suction Bomb",
	special: "Trizooka",
	wclass: "Shooter",
	id: 70},

    {name: "Hoofz Daulie Squelchers",
    sub: "Point Sensor",
    special: "Splattercolor Screen",
    wclass: "Daulie",
	id: 71},

    {name: "Hornz Dread Wringer",
    sub: "Curling Bomb",
    special: "Crab Tank",
    wclass: "Slosher",
	id: 72},

	{name: "Hydra Splatling",
	sub: "Autobomb",
	special: "Booyah Bomb",
	wclass: "Splatling",
	id: 73},

	{name: "Inkbrush",
	sub: "Splat Bomb",
	special: "Killer Wail 5.1",
	wclass: "Brush",
	id: 74},

	{name: "Inkbrush Nouveau",
	sub: "Ink Mine",
	special: "Ultra Stamp",
	wclass: "Brush",
	id: 75},

	{name: "Inkline Tri-Stringer",
	sub: "Sprinkler",
	special: "Super Chump",
	wclass: "Stringer",
	id: 76},

	{name: "Jet Squelcher",
	sub: "Angle Shooter",
	special: "Ink Vac",
	wclass: "Shooter",
	id: 77},

    {name: "Jet Squelcher COB-R",
    sub: "Burst Bomb",
    special: "Triple Splashdown",
    wclass: "Shooter",
	id: 78},

	{name: "Krak-On Splat Roller",
	sub: "Squid Beakon",
	special: "Kraken Royale",
	wclass: "Roller",
	id: 79},

	{name: "L-3 Nozzlenose",
	sub: "Curling Bomb",
	special: "Crab Tank",
	wclass: "Shooter",
	id: 80},

	{name: "L-3 Nozzlenose D",
	sub: "Burst Bomb",
	special: "Ultra Stamp",
	wclass: "Shooter",
	id: 81},

	{name: "Light Tetra Dualies",
	sub: "Sprinkler",
	special: "Zipcaster",
	wclass: "Dualie",
	id: 82},

	{name: "Luna Blaster",
	sub: "Splat Bomb",
	special: "Zipcaster",
	wclass: "Blaster",
	id: 83},

	{name: "Luna Blaster Neo",
	sub: "Fizzy Bomb",
	special: "Ultra Stamp",
	wclass: "Blaster",
	id: 84},

	{name: "Mini Splatling",
	sub: "Burst Bomb",
	special: "Ultra Stamp",
	wclass: "Splatling",
	id: 85},

    {name: "Mini Splatling RTL-R",
    sub: "Squid Beakon",
    special: "Trizooka",
    wclass: "Splatling",
	id: 86},

	{name: "Mint Decavitator",
	sub: "Suction Bomb",
	special: "Big Bubbler",
	wclass: "Splatana",
	id: 87},

	{name: "N-ZAP 85",
	sub: "Suction Bomb",
	special: "Tacticooler",
	wclass: "Shooter",
	id: 88},

	{name: "N-ZAP 89",
	sub: "Autobomb",
	special: "Super Chump",
	wclass: "Shooter",
	id: 89},

	{name: "Nautilus 47",
	sub: "Point Sensor",
	special: "Ink Storm",
	wclass: "Splatling",
	id: 90},

	{name: "Nautilus 79",
	sub: "Suction Bomb",
	special: "Triple Splashdown",
	wclass: "Splatling",
	id: 91},

	{name: "Neo Splash-o-matic",
	sub: "Suction Bomb",
	special: "Triple Inkstrike",
	wclass: "Shooter",
	id: 92},

	{name: "Neo Sploosh-o-matic",
	sub: "Squid Beakon",
	special: "Killer Wail 5.1",
	wclass: "Shooter",
	id: 93},

	{name: "New Squiffer",
	sub: "Autobomb",
	special: "Zipcaster",
	wclass: "Charger",
	id: 94},

	{name: "Octo Shot Replica",
	sub: "Splat Bomb",
	special: "Triple Inkstrike",
	wclass: "Shooter",
	id: 95},

	{name: "Octobrush",
	sub: "Suction Bomb",
	special: "Zipcaster",
	wclass: "Brush",
	id: 96},

	{name: "Octobrush Nouveau",
	sub: "Squid Beakon",
	special: "Ink Storm",
	wclass: "Brush",
	id: 97},

	{name: "Order Blaster Replica",
	sub: "Splat Bomb",
	special: "Zipcaster",
	wclass: "Blaster",
	id: 98},

	{name: "Order Brella Replica",
	sub: "Sprinkler",
	special: "Triple Inkstrike",
	wclass: "Brella",
	id: 99},

	{name: "Order Charger Replica",
	sub: "Splat Bomb",
	special: "Ink Vac",
	wclass: "Charger",
	id: 100},

	{name: "Order Dualie Replicas",
	sub: "Suction Bomb",
	special: "Crab Tank",
	wclass: "Dualie",
	id: 101},

	{name: "Order Roller Replica",
	sub: "Curling Bomb",
	special: "Big Bubbler",
	wclass: "Roller",
	id: 102},

	{name: "Order Shot Replica",
	sub: "Suction Bomb",
	special: "Trizooka",
	wclass: "Shooter",
	id: 103},

	{name: "Order Slosher Replica",
	sub: "Splat Bomb",
	special: "Triple Inkstrike",
	wclass: "Slosher",
	id: 104},

	{name: "Order Splatana Replica",
	sub: "Burst Bomb",
	special: "Zipcaster",
	wclass: "Splatana",
	id: 105},

	{name: "Order Splatling Replica",
	sub: "Sprinkler",
	special: "Wave Breaker",
	wclass: "Splatling",
	id: 106},

	{name: "Order Stringer Replica",
	sub: "Toxic Mist",
	special: "Killer Wail 5.1",
	wclass: "Stringer",
	id: 107},

	{name: "Orderbrush Replica",
	sub: "Suction Bomb",
	special: "Zipcaster",
	wclass: "Brush",
	id: 108},

	{name: "Painbrush",
	sub: "Curling Bomb",
	special: "Wave Breaker",
	wclass: "Brush",
	id: 109},

    {name: "Painbrush BRN-Z",
    sub: "Splash Wall",
    special: "Trizooka",
    wclass: "Brush",
	id: 110},

	{name: "Painbrush Nouveau",
	sub: "Point Sensor",
	special: "Tenta Missiles",
	wclass: "Brush",
	id: 111},

    {name: "Patternz Undercover Brella",
    sub: "Curling Bomb",
    special: "Killer Wail 5.1",
    wclass: "Brella",
	id: 112},

    {name: "Planetz Big Swig Roller",
    sub: "Torpedo",
    special: "Triple Splashdown",
    wclass: "Roller",
	id: 113},

	{name: "Range Blaster",
	sub: "Suction Bomb",
	special: "Wave Breaker",
	wclass: "Blaster",
	id: 114},

	{name: "Rapid Blaster",
	sub: "Ink Mine",
	special: "Triple Inkstrike",
	wclass: "Blaster",
	id: 115},

	{name: "Rapid Blaster Deco",
	sub: "Torpedo",
	special: "Inkjet",
	wclass: "Blaster",
	id: 116},

	{name: "Rapid Blaster Pro",
	sub: "Toxic Mist",
	special: "Ink Vac",
	wclass: "Blaster",
	id: 117},

	{name: "Rapid Blaster Pro Deco",
	sub: "Angle Shooter",
	special: "Killer Wail 5.1",
	wclass: "Blaster",
	id: 118},

    {name: "Rapid Blaster Pro WNT-R",
    sub: "Suction Bomb",
    special: "Tacticooler",
    wclass: "Blaster",
	id: 119},

	{name: "Recycled Brella 24 Mk I",
	sub: "Angle Shooter",
	special: "Big Bubbler",
	wclass: "Brella",
	id: 120},

	{name: "Recycled Brella 24 Mk II",
	sub: "Toxic Mist",
	special: "Triple Splashdown",
	wclass: "Brella",
	id: 121},

	{name: "REEF-LUX 450",
	sub: "Curling Bomb",
	special: "Tenta Missiles",
	wclass: "Stringer",
	id: 122},

	{name: "REEF-LUX 450 Deco",
	sub: "Splash Wall",
	special: "Reefslider",
	wclass: "Stringer",
	id: 123},

    {name: "REEF-LUX 450 MIL-K",
    sub: "Torpedo",
    special: "Booyah Bomb",
    wclass: "Stringer",
	id: 124},

	{name: "S-BLAST 91",
	sub: "Burst Bomb",
	special: "Booyah Bomb",
	wclass: "Blaster",
	id: 125},

	{name: "S-BLAST 92",
	sub: "Sprinkler",
	special: "Reefslider",
	wclass: "Blaster",
	id: 126},

	{name: "Slosher",
	sub: "Splat Bomb",
	special: "Triple Inkstrike",
	wclass: "Slosher",
	id: 127},

	{name: "Slosher Deco",
	sub: "Angle Shooter",
	special: "Zipcaster",
	wclass: "Slosher",
	id: 128},

	{name: "Sloshing Machine",
	sub: "Fizzy Bomb",
	special: "Booyah Bomb",
	wclass: "Slosher",
	id: 129},

	{name: "Sloshing Machine Neo",
	sub: "Point Sensor",
	special: "Trizooka",
	wclass: "Slosher",
	id: 130},

	{name: "Snipewriter 5B",
	sub: "Splash Wall",
	special: "Ink Storm",
	wclass: "Charger",
	id: 131},

	{name: "Snipewriter 5H",
	sub: "Sprinkler",
	special: "Tacticooler",
	wclass: "Charger",
	id: 132},

	{name: "Sorella Brella",
	sub: "Autobomb",
	special: "Inkjet",
	wclass: "Brella",
	id: 133},

	{name: "Splash-o-matic",
	sub: "Burst Bomb",
	special: "Crab Tank",
	wclass: "Shooter",
	id: 134},

    {name: "Splash-o-matic GCK-O",
    sub: "Toxic Mist",
    special: "Ink Storm",
    wclass: "Shooter",
	id: 135},

	{name: "Splat Brella",
	sub: "Sprinkler",
	special: "Triple Inkstrike",
	wclass: "Brella",
	id: 136},

	{name: "Splat Charger",
	sub: "Splat Bomb",
	special: "Ink Vac",
	wclass: "Charger",
	id: 137},

    {name: "Splat Charger CAM-O",
    sub: "Sprinkler",
    special: "Crab Tank",
    wclass: "Charger",
	id: 138},

	{name: "Splat Dualies",
	sub: "Suction Bomb",
	special: "Crab Tank",
	wclass: "Dualie",
	id: 139},

	{name: "Splat Roller",
	sub: "Curling Bomb",
	special: "Big Bubbler",
	wclass: "Roller",
	id: 140},

	{name: "Splatana Stamper",
	sub: "Burst Bomb",
	special: "Zipcaster",
	wclass: "Splatana",
	id: 141},

	{name: "Splatana Stamper Nouveau",
	sub: "Toxic Mist",
	special: "Crab Tank",
	wclass: "Splatana",
	id: 142},

	{name: "Splatana Wiper",
	sub: "Torpedo",
	special: "Ultra Stamp",
	wclass: "Splatana",
	id: 143},

	{name: "Splatana Wiper Deco",
	sub: "Squid Beakon",
	special: "Tenta Missiles",
	wclass: "Splatana",
	id: 144},

    {name: "Splatana Wiper RUS-T",
    sub: "Curling Bomb",
    special: "Trizooka",
    wclass: "Splatana",
	id: 145},

	{name: "Splatterscope",
	sub: "Splat Bomb",
	special: "Ink Vac",
	wclass: "Charger",
	id: 146},

    {name: "Splatterscope CAM-O",
    sub: "Sprinkler",
    special: "Crab Tank",
    wclass: "Charger",
	id: 147},

	{name: "Splattershot",
	sub: "Suction Bomb",
	special: "Trizooka",
	wclass: "Shooter",
	id: 148},

    {name: "Splattershot Pro FRZ-N",
    sub: "Splat Bomb",
    special: "Tenta Missiles",
    wclass: "Shooter",
	id: 149},

	{name: "Splattershot Jr.",
	sub: "Splat Bomb",
	special: "Big Bubbler",
	wclass: "Shooter",
	id: 150},

	{name: "Splattershot Nova",
	sub: "Point Sensor",
	special: "Killer Wail 5.1",
	wclass: "Shooter",
	id: 151},

	{name: "Splattershot Pro",
	sub: "Angle Shooter",
	special: "Crab Tank",
	wclass: "Shooter",
	id: 152},

	{name: "Sploosh-o-matic",
	sub: "Curling Bomb",
	special: "Ultra Stamp",
	wclass: "Shooter",
	id: 153},

	{name: "Squeezer",
	sub: "Splash Wall",
	special: "Trizooka",
	wclass: "Shooter",
	id: 154},

    {name: "Starz Dynamo Roller",
    sub: "Point Sensor",
    special: "Killer Wail 5.1",
    wclass: "Roller",
	id: 155},

    {name: "Stickerz Splatana Stamper",
    sub: "Autobomb",
    special: "Booyah Bomb",
    wclass: "Splatana",
	id: 156},

	{name: "Tenta Brella",
	sub: "Squid Beakon",
	special: "Ink Vac",
	wclass: "Brella",
	id: 157},

    {name: "Tenta Brella CRE-M",
    sub: "Toxic Mist",
    special: "Super Chump",
    wclass: "Brella",
	id: 158},

	{name: "Tenta Sorella Brella",
	sub: "Ink Mine",
	special: "Trizooka",
	wclass: "Brella",
	id: 159},

	{name: "Tentatek Splattershot",
	sub: "Splat Bomb",
	special: "Triple Inkstrike",
	wclass: "Shooter",
	id: 160},

    {name: "Torrentz Hydra Splatling",
    sub: "Sprinkler",
    special: "Big Bubbler",
    wclass: "Splatling",
	id: 161},

	{name: "Tri-Slosher",
	sub: "Toxic Mist",
	special: "Inkjet",
	wclass: "Slosher",
	id: 162},

    {name: "Tri-Slosher ASH-N",
    sub: "Splat Bomb",
    special: "Splattercolor Screen",
    wclass: "Slosher",
	id: 163},

	{name: "Tri-Slosher Nouveau",
	sub: "Fizzy Bomb",
	special: "Tacticooler",
	wclass: "Slosher",
	id: 164},

	{name: "Tri-Stringer",
	sub: "Toxic Mist",
	special: "Killer Wail 5.1",
	wclass: "Stringer",
	id: 165},

    {name: "Twinklez Splat Dualies",
    sub: "Fizzy Bomb",
    special: "Big Bubbler",
    wclass: "Dualie",
	id: 166},

	{name: "Undercover Brella",
	sub: "Ink Mine",
	special: "Reefslider",
	wclass: "Brella",
	id: 167},

	{name: "Undercover Sorella Brella",
	sub: "Torpedo",
	special: "Splattercolor Screen",
	wclass: "Brella",
	id: 168},

	{name: "Wellstring V",
	sub: "Autobomb",
	special: "Ultra Stamp",
	wclass: "Stringer",
	id: 169},

	{name: "ZF Splat Charger",
	sub: "Splash Wall",
	special: "Triple Inkstrike",
	wclass: "Charger",
	id: 170},

	{name: "ZF Splatterscope",
	sub: "Splash Wall",
	special: "Triple Inkstrike",
	wclass: "Charger",
	id: 171},

	{name: "Zink Mini Splatling",
	sub: "Toxic Mist",
	special: "Big Bubbler",
	wclass: "Splatling",
	id: 172}
]